"""Canonical chunk persistence. Source of truth for both indexes."""
from ingestion.chunking import Chunk

def save_chunks(chunks: list[Chunk]) -> None: ...
def load_all_chunks() -> list[Chunk]: ...
def get_chunks(chunk_ids: list[str]) -> list[Chunk]: ...
def clear() -> None: ...