"""Embedded Qdrant collection over chunk vectors."""
import numpy as np

def upsert(chunk_ids: list[str], vectors: np.ndarray) -> None: ...
def search(query_vector: np.ndarray, top_k: int) -> list[tuple[str, float]]: ...
def clear() -> None: ...